_schema-version: '3.1'
ID: RiskManagementTwo
version: 1.0.0
description: A simple CAP project.
parameters:
  deploy_mode: html5-repo
  enable-parallel-deployments: true
build-parameters:
  before-all:
    - builder: custom
      commands:
        - rm -rf build/dist
        - mkdir -p build/dist
        - rm -rf build/ui-deployer
        - mkdir -p build/ui-deployer
    - builder: custom
      commands:
        - npm install --production
        - >-
          bash -c "cds -v | grep 'cds-dk' || npm i --production --no-save
          @sap/cds-dk @sap/mdk-tools"
        - bash -c "export PATH=$PATH:$(pwd)/node_modules/.bin"
        - cds build --production
  after-all:
    - builder: custom
      commands:
        - npm install
modules:
  - name: RiskManagementTwo-riskmanagementtwo.riskmananagementtwo
    type: html5
    path: app/riskmanagementtwo.riskmananagementtwo
    build-parameters:
      builder: custom
      commands:
        - rm -rf dist-zip dist
        - npm install
        - >-
          npx -p @ui5/cli@^3.0.0 ui5 build --dest dist
          --include-task=generateCachebusterInfo
        - mkdir dist-zip
        - >-
          bash -c "cd dist && npx bestzip
          ../dist-zip/riskmanagementtworiskmananagementtwo.zip *"
      _artifactName: riskmanagementtworiskmananagementtwo.zip
      supported-platforms: []
      build-result: dist-zip
  - name: RiskManagementTwo-db-deployer
    type: hdb
    path: gen/db
    parameters:
      buildpack: nodejs_buildpack
    build-parameters:
      builder: npm
      ignore:
        - node_modules
        - package-lock.json
    requires:
      - name: RiskManagementTwo-service-uaa
      - name: RiskManagementTwo-service-db
  - name: RiskManagementTwo-srv
    type: nodejs
    path: gen/srv
    parameters:
      memory: 256MB
    provides:
      - name: srv-api
        properties:
          srv-url: ${default-url}
    build-parameters:
      builder: npm
      ignore:
        - node_modules
        - package-lock.json
    requires:
      - name: RiskManagementTwo-service-uaa
      - name: RiskManagementTwo-service-db
      - name: RiskManagementTwo-service-destination
      - name: RiskManagementTwo-service-metadata
      - name: RiskManagementTwo-service-connectivity
      - name: RiskManagementTwo-service-logs
  - name: RiskManagementTwo-aux-destinations
    type: com.sap.application.content
    parameters:
      content:
        subaccount:
          existing_destinations_policy: update
          destinations:
            - Authentication: OAuth2UserTokenExchange
              Name: RiskManagementTwo-service-uaa
              ServiceInstanceName: RiskManagementTwo-uaa
              ServiceKeyName: RiskManagementTwo-uaa-key
              sap.cloud.service: lcap.RiskManagementTwo
            - Authentication: OAuth2UserTokenExchange
              Name: RiskManagementTwo-app-srv
              TokenServiceInstanceName: RiskManagementTwo-uaa
              TokenServiceKeyName: RiskManagementTwo-uaa-key
              URL: ~{srv-api/srv-url}
              sap.cloud.service: lcap.RiskManagementTwo
            - Name: RiskManagementTwo-service-html5-apps-repo-host
              ServiceInstanceName: RiskManagementTwo-html5-apps-repo-host
              ServiceKeyName: RiskManagementTwo-html5-apps-repo-host-key
              sap.cloud.service: lcap.RiskManagementTwo
            - Authentication: OAuth2UserTokenExchange
              Name: RiskManagementTwo-RiskManagementTwoService
              TokenServiceInstanceName: RiskManagementTwo-uaa
              TokenServiceKeyName: RiskManagementTwo-uaa-key
              URL: ~{srv-api/srv-url}/service/RiskManagementTwoService
              sap.cloud.service: lcap.RiskManagementTwo
              sap.applicationdevelopment.actions.enabled: false
              sap.build.usage: CAP
              sap.processautomation.enabled: false
              HTML5.DynamicDestination: false
              WebIDEEnabled: false
              MobileEnabled: false
              AppgyverEnabled: false
    build-parameters:
      no-source: true
    requires:
      - name: RiskManagementTwo-service-uaa
        parameters:
          service-key:
            name: RiskManagementTwo-uaa-key
      - name: srv-api
      - name: RiskManagementTwo-service-html5-apps-repo-host
        parameters:
          service-key:
            name: RiskManagementTwo-html5-apps-repo-host-key
      - name: RiskManagementTwo-service-destination
        parameters:
          content-target: true
  - name: RiskManagementTwo-launchpad
    type: html5
    path: build/launchpad
    build-parameters:
      builder: custom
      commands:
        - npm install
        - >-
          npx -p @ui5/cli@^3.0.0 ui5 build --dest dist
          --include-task=generateCachebusterInfo
        - bash -c "cd dist && npx bestzip ../../../build/dist/launchpad.zip *"
        - rm -rf dist
      _artifactName: launchpad.zip
      supported-platforms: []
      build-result: ../../build/dist
  - name: RiskManagementTwo-aux-ui-deployer
    type: com.sap.application.content
    path: build/ui-deployer
    build-parameters:
      build-result: resources
      requires:
        - name: RiskManagementTwo-riskmanagementtwo.riskmananagementtwo
          artifacts:
            - riskmanagementtworiskmananagementtwo.zip
          target-path: resources
        - name: RiskManagementTwo-launchpad
          artifacts:
            - launchpad.zip
          target-path: resources
    requires:
      - name: RiskManagementTwo-service-html5-apps-repo-host
        parameters:
          content-target: true
resources:
  - type: org.cloudfoundry.managed-service
    name: RiskManagementTwo-service-uaa
    parameters:
      service: xsuaa
      service-plan: application
      service-name: RiskManagementTwo-uaa
      path: xs-security.json
      config:
        oauth2-configuration:
          redirect-uris:
            - https://*.${default-domain}/login/*
          credential-types:
            - binding-secret
            - x509
        xsappname: RiskManagementTwo-${space}
        role-collections:
          - description: RiskViewer
            name: RiskManagementTwo-RiskViewer-${space}
            role-template-references:
              - $XSAPPNAME.RiskViewer
          - description: RiskManager
            name: RiskManagementTwo-RiskManager-${space}
            role-template-references:
              - $XSAPPNAME.RiskManager
  - type: org.cloudfoundry.managed-service
    name: RiskManagementTwo-service-db
    parameters:
      service: hana
      service-plan: hdi-shared
      service-name: RiskManagementTwo-db
  - type: org.cloudfoundry.managed-service
    name: RiskManagementTwo-service-destination
    parameters:
      service: destination
      service-plan: lite
      service-name: RiskManagementTwo-destination
      config:
        HTML5Runtime_enabled: true
        version: 1.0.0
  - type: org.cloudfoundry.user-provided-service
    name: RiskManagementTwo-service-metadata
    parameters:
      service: metadata
      service-plan: standard
      service-name: RiskManagementTwo-metadata
      config:
        default-domain: ${default-domain}
  - type: org.cloudfoundry.managed-service
    name: RiskManagementTwo-service-connectivity
    parameters:
      service: connectivity
      service-plan: lite
      service-name: RiskManagementTwo-connectivity
  - type: org.cloudfoundry.managed-service
    name: RiskManagementTwo-service-logs
    parameters:
      service: application-logs
      service-plan: lite
      service-name: RiskManagementTwo-logs
  - type: org.cloudfoundry.managed-service
    name: RiskManagementTwo-service-html5-apps-repo-host
    parameters:
      service: html5-apps-repo
      service-plan: app-host
      service-name: RiskManagementTwo-html5-apps-repo-host
